### PR TITLE
Grab Shantanu's docker files

### PR DESCRIPTION
**Pull request by convoliution**

### CODE REVIEW

**Comment by mvartakAtVerta** [comment]
@convoliution Does ./fix-imports need to go in here?

**Comment by convoliution** [comment]
@mvartakAtVerta Good idea—will do, but ./fix-import should reeeaally actually go in the pipeline that generated the Python proto files.

**Comment by convoliution** [comment]
@mvartakAtVerta I just remembered that this isn't trivial to do; `./fix-imports` uses macOS's `sed`'s syntax, but Linux's `sed` has a different syntax and the docker container I believe uses Debian. Not sure if it's a good use of time right now to look up how to make the script compatible.

**Comment by convoliution** [comment]
I did it anyway.

**Pull request merged**
